// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5vyLfjTVEUZ2OKG9KlMXLq1ADn-RUHBA',
    appId: '1:286626353466:web:738159c73a92b102cb0003',
    messagingSenderId: '286626353466',
    projectId: 'pathshala-5699d',
    authDomain: 'pathshala-5699d.firebaseapp.com',
    storageBucket: 'pathshala-5699d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdv0t5NygmSLCqd0Pelu0z5PxmkR0E6-Y',
    appId: '1:286626353466:android:1020db9324ac2a96cb0003',
    messagingSenderId: '286626353466',
    projectId: 'pathshala-5699d',
    storageBucket: 'pathshala-5699d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBs-wleb9DNiIDXvgrZKxFTjcurlnqDpwg',
    appId: '1:286626353466:ios:62f05568660620cdcb0003',
    messagingSenderId: '286626353466',
    projectId: 'pathshala-5699d',
    storageBucket: 'pathshala-5699d.firebasestorage.app',
    iosBundleId: 'com.example.pathshala',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBs-wleb9DNiIDXvgrZKxFTjcurlnqDpwg',
    appId: '1:286626353466:ios:62f05568660620cdcb0003',
    messagingSenderId: '286626353466',
    projectId: 'pathshala-5699d',
    storageBucket: 'pathshala-5699d.firebasestorage.app',
    iosBundleId: 'com.example.pathshala',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5vyLfjTVEUZ2OKG9KlMXLq1ADn-RUHBA',
    appId: '1:286626353466:web:71d2b4afadfec819cb0003',
    messagingSenderId: '286626353466',
    projectId: 'pathshala-5699d',
    authDomain: 'pathshala-5699d.firebaseapp.com',
    storageBucket: 'pathshala-5699d.firebasestorage.app',
  );
}
